### ISSUE TITLE
basics.py classification fails with IndexError: index 1 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by Lapayo** [alejandromolinaml/SPFlow#2] opened 2018-09-16 11:08 UTC
While running the basics.py classification example I get the following error:
```
Traceback (most recent call last):
  File "basics.py", line 226, in <module>
    classification()
  File "basics.py", line 143, in classification
    learn_parametric, 2)
  File "spflow/src/spn/algorithms/LearningWrappers.py", line 25, in learn_classifier
    branch = spn_learn_wrapper(data[data[:, label_idx] == label, :], ds_context, cpus=cpus, rand_gen=rand_gen)
  File "spflow/src/spn/algorithms/LearningWrappers.py", line 117, in learn_parametric
    return learn_param(data, ds_context, cols, rows, min_instances_slice, threshold, ohe)
  File "spflow/src/spn/algorithms/LearningWrappers.py", line 112, in learn_param
    return learn_structure(data, ds_context, split_rows, split_cols, leaves, nextop)
  File "spflow/src/spn/algorithms/StructureLearning.py", line 208, in learn_structure
    child_data_slice = data_slicer(data_slice, scope_slice, num_conditional_cols)
  File "spflow/src/spn/algorithms/StructureLearning.py", line 86, in default_slicer
    return data[:, cols[0]].reshape((-1, 1))
IndexError: index 1 is out of bounds for axis 1 with size 1
```

Is the example outdated or is this a fault in the learning code?

Thanks in advance!

**Comment by xiaotingshao** [comment] 2018-09-18 09:40
the bug was caused by wrong column index in data slicer and it should be fixed now in the new version.

**Comment by tfleck90** [comment] 2018-09-19 07:49
Thank you very much, 52672fb1 seems to fix the bug for me.

**Closed** 2018-09-19 08:07 UTC
